### ISSUE TITLE
Ivar sheep barn food feed takes precedence of grass

### ISSUE THREAD

**Issue by b-gyula** [MapsOfNorway/rennebugs#109]
As I've learned the sheep barns of Norway require _*BOTH*_ grass and silage to let the sheep produce wool. 
But if you pile both grass and silage at the load area, only grass is used.
And when silage runs out, wool production stops!
![Ivar sheep barn food feed](https://user-images.githubusercontent.com/27079815/185263879-2e974af9-baaf-405c-9961-47b07c7454fa.gif)
![Ivar sheep barn food feed loading area](https://user-images.githubusercontent.com/27079815/185263922-118c67e2-54bd-4cb4-9ab9-9aa0e835d394.gif)
![Ivar sheep barn food feed 1](https://user-images.githubusercontent.com/27079815/185263943-47653d8f-6ed4-4ab5-bf54-eef582411b87.gif)

**Comment by OlaHaldor** [comment]
I can't decide the order of which food is loaded first as far as I know. 
The food is set to be consumed in parallel, meaning both food types should be consumed at the same time.

But that only tells the game to use both, not to load both I guess. 
Perhaps something to report to Giants instead of me. 
You can report it here https://feedback.giants-software.com/

I wonder if this is true for other, default animal pens where you have two or more types of food you need to deliver, that it picks one over the other instead of both at the same time.

**Comment by b-gyula** [comment]
You might be absolutely right. I've seen similar with the original cow barn where I've given both grass and TMR. 
I wonder how the pig barn works... I'll check it

**Comment by OlaHaldor** [comment]
Any news?
