### ISSUE TITLE
Straw and cows?

### ISSUE THREAD

**Issue by TrainzmanUK** [MapsOfNorway/rennebugs#47]
I take it cows do not need straw as there is no where to add it to the barn?
Yet it shows straw in the animal dialogue?
Also there is no info panel pop up near cow or sheep barns? the only way is through the animal settings using the ESC key? 

 ![image](https://user-images.githubusercontent.com/47663166/179466867-df872f1d-7c80-48e1-892f-f2943c2dc37a.png)

**Comment by OlaHaldor** [comment]
This is a complex matter.

There is no way to disable the straw from being visible in the UI, as far as I know. If it is, I'd love to know how.

Solid manure is not really a thing in the region, let alone for the country in whole. Very few use it. Instead, liquid slurry is the way to go.

I should make that more clear somehow. If I can remove the straw from the UI that's the best I guess.

Now, the info panel should work for the barns that do not have multiple placeable types.
The starter farm cow barn should have the panel. If not, it's a matter of making the box larger. I'll have a look into that when I'm back from vacation.

The starter sheep barn and Hol cow barn cannot show the info panel because it's a combination of silo and animalHusbandry, and bunkerSilo and animalHusbandry. Thus the game doesn't know what info to show, resulting in a conflict and the game behaves in unexpected ways.

Having the function of a silo and bunkerSilo inside the barn, as in real life, was crucial to make work for the experience. Sadly the side effect is the lack of the info panel. 

I'll clarify this in a document covering all farms and buildings early august when I'm back.

**Comment by BeardsViking** [comment]
So the animal dont need straw. because i have tryed to deliverd, but it not accept it
![Skjermbilde (17)](https://user-images.githubusercontent.com/109419474/179477745-26f14497-6d59-489f-a675-c3b45dd4e37d.png)

**Comment by BeardsViking** [comment]
Is it posible to implement straw to the animal ? thats normal in norway to use straw.

**Comment by OlaHaldor** [comment]
Technically possible. But since no barns there have a manure pit outside I think it's best you build it yourself as an extension.

**Comment by BeardsViking** [comment]
Do they not use the manure at some farm in Rennebu ?

**Comment by BeardsViking** [comment]
That's a good solution.
Is it possible to activate the straw for those who want? Is it just some changes in the map file?

Of topics, but are the pig and chicken farms in Rennebu?

**Comment by BeardsViking** [comment]
This is the barn at Hoels mølle.
This entrance to the basement are for manure I think 
![image](https://user-images.githubusercontent.com/109419474/179575158-99ee5c69-7499-42f5-be07-fa6d9a683f4e.png)

**Comment by BeardsViking** [comment]
I understand. You doing a good job 😁

**Comment by OlaHaldor** [comment]
You know what; the default barns don't take straw bales either unless I'm completely mistaken.
Could you test and verify?

**Comment by TrainzmanUK** [comment]
Most barns only take loose or blown straw

**Comment by KindCoder-no** [comment]
You can use one of these
![image](https://user-images.githubusercontent.com/40148297/181373238-bd5ebae3-9d3d-48e5-bedf-6b8078efe33d.png)
