### ISSUE TITLE
Farm in the alps. 

### ISSUE THREAD

**Issue by Tordenskroll** [MapsOfNorway/rennebugs#57]
I wuld like to have the possibility to build at have the abbility to make a farm in this place i have made a circle around.
![rennebu hjørne](https://user-images.githubusercontent.com/71593858/179800145-567a44eb-d0e9-437f-8536-c1d10ca433df.png)

**Comment by OlaHaldor** [comment]
This is not possible as it is outside the playable area, for two reasons.

- The graphics bugs out (items, vehicles etc disappear the further up and away you are)
- The lake does not exist. It is there in the map because it is where it is irl. Ingame the snowy mountain covers the lake so it stays within the playable area to be rendered. If the mountain was located ingame where it is irl it would not render.
