### ISSUE TITLE
Season issues

### ISSUE THREAD

**Issue by MariusTro** [MapsOfNorway/rennebugs#80]
I have my game set to 2 days in every month. Finished off autumn with grass harvest. Then skipped around until snow was gone. The snow came in april and stayed in all may (4 days ingame) then first day in june the grass was ready to harvest. No growing needed after snow? Just instant growth?

**Comment by OlaHaldor** [comment]
That's an interesting punch in the face. It's not uncommon to snow there in April and May., but I'm not sure I can alter the growth based on whether there _is_ snow.

**Comment by Smurfenstein** [comment]
Unfortunately weather and growth is totally unconnected in FS22. Did you wait a couple of minutes after skipping time? There might be snow cover when you start a day but then not after a minute or so, takes a while for it to update because of map size. Could increase the minimum temps for april to 0 celcius to make snow go away maybe ?

**Comment by Smurfenstein** [comment]
Took a look at it in the maps_growth_norge.xml. Grass probably need to be in state 1 in period 1 and 2 (march and april) maybe period 3 (may) aswell. At moment grass can be ready to harvest(state 3) in april.

**Comment by Smurfenstein** [comment]
looks like I managed to fix the grass..  uploaded the file to discord because I couldn't make pull request

**Comment by Smurfenstein** [comment]
These files should fix it
https://1drv.ms/u/s!Ag4locAb1gz3hpViqpKzpTEd-BnkbQ?e=RwetbW
https://1drv.ms/u/s!Ag4locAb1gz3hpZbDpNw7BcWt_Wtzw?e=ZqsCZa

**Comment by OlaHaldor** [comment]
Thanks a lot for your effort. Will be part of a future update. :)
