### ISSUE TITLE
Can't unload loose material in bunker silo

### ISSUE THREAD

**Issue by TheOnlyManatee** [MapsOfNorway/rennebugs#82]
![FarmingSimulator2022Game 2022-07-27 09-53-46](https://user-images.githubusercontent.com/109970529/181193230-7bf4f2de-ab63-46a0-8240-5e15fe9795df.png)
Tried placing a standard bunker silo in this area, but can't unload into it. "This action cannot be performed here" when trying. If I drive around the area with the trailer the "Unload here" prompt seems to disappear close to the placed silo, and other random places. 
Similarly, when  mowing the standard meadow grass in that area, the cut grass is not dropped by the mower some places, like a permission problem or something.
Not sure what happens, but seems like the land cant be used entirely.

**Comment by OlaHaldor** [comment]
I have a hunch what it might be. Just let me get home from vacation first.

**Comment by OlaHaldor** [comment]
I made a change to tipCol last night to test to test. You can now empty into bunkers. 

I'm not so familiar with bunkers in FS. Are you supposed to get a big "unload" text in the center of the screen like when you're at the grain mill? Or is it only noticeable with a "unload here" text in the top left?

**Comment by TheOnlyManatee** [comment]
Tested the same bunker on Elm creeck, it doesn't give you the big prompt in the center of the screen, only the "Unload here" is visible in the top left.

**Comment by OlaHaldor** [comment]
Alright. So that's a good thing. It works now with the fix I did. Does not require a new savegame as far as I can tell.

On the other hand it can be confusing when you see "unload here" everywhere and not only in bunkers. 

I have a lot of requests and messages about players who want to be able to tip anywhere. From a gameplay perspective I don't think it should say "unload here" everywhere but that's nothing I can control except for not allowing to unload everywhere.

**Comment by OlaHaldor** [comment]
The fix is published on my discord in the **public-testing** channel if you'd like to try. It will require basic file handling skills, so it's not too hard to update and overwrite the old files.
